# Generated by Django 5.1.5 on 2025-12-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ATTENDANCE_EDIT_REQUEST', 'Attendance Edit Request'), ('ATTENDANCE_EDIT_APPROVED', 'Attendance Edit Approved'), ('ATTENDANCE_EDIT_REJECTED', 'Attendance Edit Rejected'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder'), ('WFH_REQUEST', 'Work From Home Request'), ('WFH_APPROVED', 'Work From Home Approved'), ('WFH_REJECTED', 'Work From Home Rejected')], max_length=50),
        ),
    ]
