# Generated by Django 5.1.5 on 2026-01-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ATTENDANCE_EDIT_REQUEST', 'Attendance Edit Request'), ('ATTENDANCE_EDIT_APPROVED', 'Attendance Edit Approved'), ('ATTENDANCE_EDIT_REJECTED', 'Attendance Edit Rejected'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('SYSTEM', 'System Notification'), ('REMINDER', 'Reminder'), ('WFH_REQUEST', 'Work From Home Request'), ('WFH_APPROVED', 'Work From Home Approved'), ('WFH_REJECTED', 'Work From Home Rejected'), ('RESOURCE_REQUEST', 'Resource Request'), ('RESOURCE_APPROVED', 'Resource Approved'), ('RESOURCE_REJECTED', 'Resource Rejected'), ('RESOURCE_ASSIGNED', 'Resource Assigned'), ('RESOURCE_APPROVAL_REQUIRED', 'Resource Approval Required'), ('ASSET_REPAIR_REQUESTED', 'Asset Repair Requested')], max_length=50),
        ),
    ]
