# Generated by Django 5.1.5 on 2026-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
