# Generated by Django 5.1.5 on 2026-03-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leavetype_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
