# Generated by Django 5.1.5 on 2026-03-31 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_client_employee'),
        ('leave_management', '0003_leavetype_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ACCRUAL', 'Accrual'), ('DEDUCTION', 'Deduction'), ('EXPIRED', 'Expired'), ('ENCASHMENT', 'Encashment')], max_length=20)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remaining_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_ledgers', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_management.leavetype')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='leave_management.leaverequest')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
