# Generated by Django 5.1.5 on 2026-04-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_leaveledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_unpaid',
            field=models.BooleanField(default=False),
        ),
    ]
