# Generated by Django 5.1.5 on 2025-03-31 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_employeestatus_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_tag'], name='assets_asse_asset_t_42b762_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['employee', 'status'], name='assets_asse_employe_c83269_idx'),
        ),
    ]
