# Generated by Django 5.1.5 on 2025-03-31 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_assets_asse_asset_t_42b762_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='GOOD', max_length=20)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='assetassignment',
            name='assets_asse_employe_c83269_idx',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='is_temporary',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='returned_at',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assets',
            field=models.ManyToManyField(related_name='assignments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='assets.assetassignment'),
        ),
    ]
