# Generated by Django 5.1.5 on 2025-04-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetreturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetreturn',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/%Y/%m/%d/return/'),
        ),
        migrations.CreateModel(
            name='AssetAssignmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/%Y/%m/%d/assignment/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_images', to='assets.assetassignment')),
            ],
        ),
    ]
