# Generated by Django 5.1.5 on 2025-04-01 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetreturn_return_image_assetassignmentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_asse_asset_t_42b762_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_asse_status_347ce9_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='condition_notes',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='warranty_expiry',
        ),
        migrations.RemoveField(
            model_name='assetreturn',
            name='cleared',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assettype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='assets/after/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='assets/before/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='manager_email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')]),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetassignmentimage',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.assetassignment'),
        ),
        migrations.AlterField(
            model_name='assetassignmentimage',
            name='image',
            field=models.ImageField(upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='return_image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='asset_team_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
