# Generated by Django 5.1.5 on 2026-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_assetrepair_repair_done_under_warranty'),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name='assetrepair',
        #     new_name='assets_asse_asset_i_85e259_idx',
        #     old_name='assets_asse_asset_id_0e6f6a_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='assetrepair',
        #     new_name='assets_asse_status_c96ca7_idx',
        #     old_name='assets_asse_status_1c3a69_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='assetrepair',
        #     new_name='assets_asse_created_83a5b3_idx',
        #     old_name='assets_asse_created__9f7a8e_idx',
        # ),
        migrations.AddField(
            model_name='offboardingassetreturn',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Date when assets were returned by the user', null=True, verbose_name='Return Date'),
        ),
    ]
