# Generated by Django 5.1.5 on 2026-01-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_add_return_date_to_offboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offboardingassetreturn',
            name='return_date',
            field=models.DateField(blank=True, help_text='Date when assets were returned by the user', null=True, verbose_name='Return Date'),
        ),
    ]
