# Generated by Django 5.1.5 on 2026-03-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_change_return_date_to_datefield'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetrepair',
            new_name='assets_asse_asset_i_85e259_idx',
            old_name='assets_asse_asset_id_0e6f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='assetrepair',
            new_name='assets_asse_status_c96ca7_idx',
            old_name='assets_asse_status_1c3a69_idx',
        ),
        migrations.RenameIndex(
            model_name='assetrepair',
            new_name='assets_asse_created_83a5b3_idx',
            old_name='assets_asse_created__9f7a8e_idx',
        ),
    ]
