# Generated by Django 5.1.5 on 2025-04-07 13:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_skill', models.CharField(max_length=100)),
                ('secondary_skill', models.CharField(blank=True, max_length=100)),
                ('technical_skills', models.TextField(blank=True)),
                ('domain_skills', models.TextField(blank=True)),
                ('soft_skills', models.TextField(blank=True)),
                ('leadership_skills', models.TextField(blank=True)),
                ('education_qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='job_descriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyRateGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Onsite', 'Onsite'), ('Near_Shore', 'Near Shore'), ('Offshore', 'Offshore')], max_length=50)),
                ('business_type', models.CharField(choices=[('Pure Staffing', 'Pure Staffing'), ('Managed Services', 'Managed Services'), ('Managed Staffing', 'Managed Staffing')], max_length=50)),
                ('from_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('to_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'unique_together': {('location', 'business_type')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competency_group', models.CharField(max_length=100)),
                ('primary_skill', models.CharField(blank=True, max_length=100)),
                ('trainable', models.BooleanField(default=False)),
                ('is_replacement_indent', models.BooleanField(default=False)),
                ('emp_id_replaced', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('billing_title_in_sow', models.CharField(blank=True, max_length=100)),
                ('allocation_type', models.CharField(choices=[('Billing', 'Billing'), ('Non Billing', 'Non Billing')], max_length=50)),
                ('offer_type', models.CharField(choices=[('Employee', 'Employee'), ('Contractor', 'Contractor'), ('Contract to Hire', 'Contract to Hire')], max_length=50)),
                ('operating_model', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('allocation_start_date', models.DateField()),
                ('allocation_end_date', models.DateField(blank=True, null=True)),
                ('resource_required_date', models.DateField()),
                ('location', models.CharField(choices=[('Onsite', 'Onsite'), ('Near_Shore', 'Near Shore'), ('Offshore', 'Offshore')], max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('opportunity_probability', models.CharField(choices=[('0-25%', '0-25% - RFP/RFI/Discussion Stage'), ('25-50%', '25-50% - RFP/Proposal Submitted'), ('50-75%', '50-75% - SOW Submitted / Verbally Confirmed'), ('100%', '100% - Received Signed SOW')], max_length=50)),
                ('client_interview', models.BooleanField(default=False)),
                ('business_type', models.CharField(choices=[('Pure Staffing', 'Pure Staffing'), ('Managed Services', 'Managed Services'), ('Managed Staffing', 'Managed Staffing')], max_length=50)),
                ('bill_rate_sow_usd_hr', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_buy_rate_tag_usd_hr', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField(blank=True)),
                ('buddy_mentor_name', models.CharField(blank=True, max_length=100)),
                ('l1_panel_name', models.CharField(max_length=100)),
                ('l2_panel_name', models.CharField(blank=True, max_length=100)),
                ('job_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_requests.jobdescription')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PMORequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ri_no', models.CharField(max_length=100, unique=True)),
                ('ri_created_date', models.DateField(default=django.utils.timezone.now)),
                ('account_name', models.CharField(max_length=100)),
                ('competency_group', models.CharField(max_length=100)),
                ('billing_title_in_sow', models.CharField(blank=True, max_length=100)),
                ('primary_skill', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('operating_model', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('resource_required_date', models.DateField()),
                ('business_type', models.CharField(max_length=50)),
                ('opportunity_probability', models.CharField(max_length=50)),
                ('business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_requests.businessunit')),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pmo_request', to='resource_requests.deliveryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_request_raised_date', models.DateField(default=django.utils.timezone.now)),
                ('account_name', models.CharField(max_length=100)),
                ('engagement_manager_delivery_director', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('bdm_client_partner', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource_requests.businessunit')),
                ('request_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='resource_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='resource_requests.resourcerequest'),
        ),
    ]
