# Generated by Django 5.1.5 on 2025-04-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRateGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('business_type', models.CharField(max_length=20)),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competency_group', models.CharField(choices=[('AI/ML', 'AI/ML'), ('Cyber Security', 'Cyber Security')], max_length=50)),
                ('primary_skill', models.TextField()),
                ('secondary_skill', models.TextField(blank=True)),
                ('education_qualification', models.CharField(blank=True, max_length=100)),
                ('experience_in_years', models.CharField(blank=True, max_length=20)),
                ('certifications', models.TextField(blank=True)),
                ('job_description_text', models.TextField(blank=True)),
                ('number_of_positions', models.PositiveIntegerField(default=1)),
                ('trainable', models.BooleanField(default=False)),
                ('is_replacement_indent', models.BooleanField(default=False)),
                ('emp_id_replaced', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('billing_title_in_sow', models.CharField(blank=True, max_length=100)),
                ('allocation_type', models.CharField(choices=[('Billing', 'Billing'), ('Non Billing', 'Non Billing')], max_length=20)),
                ('offer_type', models.CharField(choices=[('Employee', 'Employee'), ('Contractor', 'Contractor'), ('Contract to Hire', 'Contract to Hire')], max_length=20)),
                ('operating_model', models.CharField(choices=[('Hybrid', 'Hybrid'), ('WFO', 'WFO')], max_length=20)),
                ('frequency', models.CharField(choices=[('2 days a week', '2 days a week'), ('3 days a week', '3 days a week'), ('Every day', 'Every day')], max_length=20)),
                ('allocation_start_date', models.DateField()),
                ('allocation_end_date', models.DateField()),
                ('resource_required_date', models.DateField()),
                ('location', models.CharField(choices=[('Offshore', 'Offshore'), ('Onsite', 'Onsite'), ('Near_Shore', 'Near_Shore')], max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('opportunity_probability', models.CharField(choices=[('0-25% - RFP/RFI/Discussion Stage', '0-25% - RFP/RFI/Discussion Stage'), ('25-50% - RFP/Proposal Submitted', '25-50% - RFP/Proposal Submitted'), ('50-75% - SOW Submitted / Verbally confirmed', '50-75% - SOW Submitted / Verbally confirmed'), ('100% - Received Signed SOW', '100% - Received Signed SOW')], max_length=50)),
                ('client_interview', models.BooleanField(default=False)),
                ('business_type', models.CharField(choices=[('Managed Services', 'Managed Services'), ('Pure Staffing', 'Pure Staffing'), ('Managed Staffing', 'Managed Staffing')], max_length=20)),
                ('bill_rate_sow_usd_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_rate_guidance_from_usd_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_rate_guidance_to_usd_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_buy_rate_tag_usd_hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField(blank=True)),
                ('verification', models.CharField(blank=True, max_length=50)),
                ('buddy_mentor_name', models.CharField(blank=True, max_length=100)),
                ('l1_panel_name', models.CharField(max_length=100)),
                ('l2_panel_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approval_token', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PMORequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ri_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('ri_created_date', models.DateField(auto_now_add=True)),
                ('business_unit', models.CharField(editable=False, max_length=50)),
                ('account_name', models.CharField(editable=False, max_length=100)),
                ('competency_group', models.CharField(editable=False, max_length=50)),
                ('billing_title_in_sow', models.CharField(editable=False, max_length=100)),
                ('primary_skill', models.CharField(editable=False, max_length=50)),
                ('designation', models.CharField(editable=False, max_length=50)),
                ('location', models.CharField(editable=False, max_length=20)),
                ('operating_model', models.CharField(editable=False, max_length=20)),
                ('frequency', models.CharField(editable=False, max_length=20)),
                ('resource_required_date', models.DateField(editable=False)),
                ('business_type', models.CharField(editable=False, max_length=20)),
                ('opportunity_probability', models.CharField(editable=False, max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pmo_request', to='resource_requests.deliveryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_request_raised_date', models.DateField(auto_now_add=True)),
                ('account_name', models.CharField(max_length=100)),
                ('engagement_manager_delivery_director', models.CharField(max_length=100)),
                ('business_unit', models.CharField(choices=[('TechOptima', 'TechOptima'), ('Branta', 'Branta')], max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('function', models.CharField(blank=True, max_length=50)),
                ('bdm_client_partner', models.CharField(blank=True, max_length=100)),
                ('request_owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='resource_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='resource_requests.resourcerequest'),
        ),
    ]
