# Generated by Django 5.1.5 on 2025-04-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='job_description',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='approval_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='approval_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='experience_in_years',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='job_description_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='number_of_positions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='secondary_skill',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='pmorequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='competency_group',
            field=models.CharField(choices=[('AI/ML', 'AI/ML'), ('Cyber Security', 'Cyber Security')], max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='primary_skill',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='business_unit',
            field=models.CharField(choices=[('TechOptima', 'TechOptima'), ('Branta', 'Branta')], max_length=50),
        ),
    ]
