# Generated by Django 5.1.5 on 2026-03-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_client_employee',
            field=models.BooleanField(default=False),
        ),
    ]
