# Generated by Django 5.1.5 on 2026-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, default='Hyderabad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_department',
            field=models.CharField(blank=True, default='Not Available', max_length=100, null=True),
        ),
    ]
