# Generated by Django 5.1.5 on 2025-03-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesshistory',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
