# Generated by Django 5.1.5 on 2025-06-10 10:05

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Access'), ('IT', 'IT Support')], default='NEW', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_management.accesslevel', verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='justification',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_management.resource', verbose_name='Resource'),
        ),
    ]
