# Generated by Django 5.1.5 on 2025-05-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Access'), ('EXTENSION', 'Access Extension'), ('REVOCATION', 'Access Revocation')], default='NEW', max_length=20, verbose_name='Request Type'),
        ),
    ]
