# Generated by Django 5.1.5 on 2025-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_accessrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='duration',
            field=models.IntegerField(blank=True, default=365, help_text='Access duration in days', null=True, verbose_name='Duration (days)'),
        ),
    ]
