# Generated by Django 5.1.5 on 2025-02-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_accessrequest_approver_email_accessrequest_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['resource_type', 'name']},
        ),
        migrations.AlterField(
            model_name='resource',
            name='environment',
            field=models.CharField(choices=[('DEV', 'Development'), ('QA', 'Quality Assurance'), ('UAT', 'User Acceptance Testing'), ('PROD', 'Production')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resource_management.resourcetype'),
        ),
    ]
