# Generated by Django 5.1.5 on 2025-05-02 07:20

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_accessrequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='justification',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Access'), ('IT', 'IT Support')], default='NEW', max_length=20, verbose_name='Request Type'),
        ),
    ]
