# Generated by Django 5.1.5 on 2025-02-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0003_alter_resource_options_alter_resource_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments', null=True),
        ),
    ]
