# Generated by Django 5.1.5 on 2026-01-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('resource_management', '0003_alter_accessrequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Access'), ('IT', 'IT Support'), ('ASSET_REPAIR', 'Asset Repair')], default='NEW', max_length=20, verbose_name='Request Type'),
        ),
    ]
