# Generated by Django 5.1.5 on 2025-05-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0003_alter_accessrequest_justification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='access_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_management.accesslevel', verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_management.resource', verbose_name='Resource'),
        ),
    ]
