# Generated by Django 5.1.5 on 2025-03-30 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0003_accessrequest_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.accesslevel', verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='approval_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Approval Token'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='approval_token_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Token Expiry'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='approver_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Approver Email'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='duration',
            field=models.IntegerField(help_text='Access duration in days', verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expires At'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='justification',
            field=models.TextField(verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Requested At'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Requires Approval'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_management.resource', verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVAL_REQUIRED', 'Approval Required'), ('APPROVER_APPROVED', 'Approver Approved'), ('APPROVER_REJECTED', 'Approver Rejected'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='ticket_number',
            field=models.CharField(default='ACC000000001', max_length=20, unique=True, verbose_name='Ticket Number'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
    ]
