# Generated by Django 5.1.5 on 2026-01-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0004_accessrequest_asset_and_request_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesshistory',
            name='action',
            field=models.TextField(),
        ),
    ]
