# Generated by Django 5.1.5 on 2026-02-17 09:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INTERN', 'Intern'), ('TRAINEE', 'Trainee'), ('JUNIOR_DEVELOPER', 'Junior Developer'), ('SOFTWARE_ENGINEER', 'Software Engineer'), ('MID_LEVEL_DEVELOPER', 'Mid-Level Developer'), ('SENIOR_DEVELOPER', 'Senior Developer'), ('LEAD_ENGINEER', 'Lead Engineer'), ('PRINCIPAL_ENGINEER', 'Principal Engineer'), ('ARCHITECT', 'Software Architect'), ('FULL_STACK_DEVELOPER', 'Full Stack Developer'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('MOBILE_APP_DEVELOPER', 'Mobile App Developer'), ('EMBEDDED_ENGINEER', 'Embedded Engineer'), ('QA_ENGINEER', 'QA Engineer'), ('MANUAL_TESTER', 'Manual Tester'), ('AUTOMATION_TESTER', 'Automation Tester'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('CLOUD_ENGINEER', 'Cloud Engineer'), ('SITE_RELIABILITY_ENGINEER', 'Site Reliability Engineer'), ('SYSTEM_ADMIN', 'System Administrator'), ('NETWORK_ENGINEER', 'Network Engineer'), ('DATA_ENGINEER', 'Data Engineer'), ('DATA_ANALYST', 'Data Analyst'), ('DATA_SCIENTIST', 'Data Scientist'), ('ML_ENGINEER', 'Machine Learning Engineer'), ('AI_ENGINEER', 'AI Engineer'), ('SECURITY_ANALYST', 'Security Analyst'), ('SECURITY_ENGINEER', 'Security Engineer'), ('UI_DESIGNER', 'UI Designer'), ('UX_DESIGNER', 'UX Designer'), ('PRODUCT_DESIGNER', 'Product Designer'), ('PRODUCT_OWNER', 'Product Owner'), ('PRODUCT_MANAGER', 'Product Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SCRUM_MASTER', 'Scrum Master'), ('BUSINESS_ANALYST', 'Business Analyst'), ('IT_SUPPORT', 'IT Support'), ('TECHNICAL_SUPPORT', 'Technical Support'), ('CUSTOMER_SUPPORT', 'Customer Support'), ('HR_EXECUTIVE', 'HR Executive'), ('HR_MANAGER', 'HR Manager'), ('ADMIN', 'Admin'), ('OFFICE_ADMIN', 'Office Administrator'), ('SALES_EXECUTIVE', 'Sales Executive'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING_EXECUTIVE', 'Marketing Executive'), ('DIGITAL_MARKETING_SPECIALIST', 'Digital Marketing Specialist'), ('SEO_SPECIALIST', 'SEO Specialist'), ('ACCOUNTANT', 'Accountant'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor'), ('LEGAL_ADVISOR', 'Legal Advisor'), ('OPERATIONS_EXECUTIVE', 'Operations Executive'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('PROCUREMENT_EXECUTIVE', 'Procurement Executive'), ('TEAM_LEAD', 'Team Lead'), ('DELIVERY_MANAGER', 'Delivery Manager'), ('ENGINEERING_MANAGER', 'Engineering Manager'), ('DIRECTOR', 'Director'), ('VP_ENGINEERING', 'VP Engineering'), ('CTO', 'Chief Technology Officer'), ('CIO', 'Chief Information Officer'), ('COO', 'Chief Operating Officer'), ('CFO', 'Chief Financial Officer'), ('CEO', 'Chief Executive Officer'), ('CONSULTANT', 'Consultant'), ('FREELANCER', 'Freelancer'), ('CONTRACTOR', 'Contractor'), ('OTHERS', 'Others')], default='INTERN', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=256)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
