# Generated by Django 5.2.1 on 2026-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('INTERN', 'Intern'), ('TRAINEE', 'Trainee'), ('JUNIOR_DEVELOPER', 'Junior Developer'), ('SOFTWARE_ENGINEER', 'Software Engineer'), ('MID_LEVEL_DEVELOPER', 'Mid-Level Developer'), ('SENIOR_DEVELOPER', 'Senior Developer'), ('LEAD_ENGINEER', 'Lead Engineer'), ('PRINCIPAL_ENGINEER', 'Principal Engineer'), ('ARCHITECT', 'Software Architect'), ('FULL_STACK_DEVELOPER', 'Full Stack Developer'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('BACKEND_DEVELOPER', 'Backend Developer'), ('MOBILE_APP_DEVELOPER', 'Mobile App Developer'), ('EMBEDDED_ENGINEER', 'Embedded Engineer'), ('QA_ENGINEER', 'QA Engineer'), ('MANUAL_TESTER', 'Manual Tester'), ('AUTOMATION_TESTER', 'Automation Tester'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('CLOUD_ENGINEER', 'Cloud Engineer'), ('SITE_RELIABILITY_ENGINEER', 'Site Reliability Engineer'), ('SYSTEM_ADMIN', 'System Administrator'), ('NETWORK_ENGINEER', 'Network Engineer'), ('DATA_ENGINEER', 'Data Engineer'), ('DATA_ANALYST', 'Data Analyst'), ('DATA_SCIENTIST', 'Data Scientist'), ('ML_ENGINEER', 'Machine Learning Engineer'), ('AI_ENGINEER', 'AI Engineer'), ('SECURITY_ANALYST', 'Security Analyst'), ('SECURITY_ENGINEER', 'Security Engineer'), ('UI_DESIGNER', 'UI Designer'), ('UX_DESIGNER', 'UX Designer'), ('PRODUCT_DESIGNER', 'Product Designer'), ('PRODUCT_OWNER', 'Product Owner'), ('PRODUCT_MANAGER', 'Product Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SCRUM_MASTER', 'Scrum Master'), ('BUSINESS_ANALYST', 'Business Analyst'), ('IT_SUPPORT', 'IT Support'), ('TECHNICAL_SUPPORT', 'Technical Support'), ('CUSTOMER_SUPPORT', 'Customer Support'), ('HR_EXECUTIVE', 'HR Executive'), ('HR_MANAGER', 'HR Manager'), ('ADMIN', 'Admin'), ('OFFICE_ADMIN', 'Office Administrator'), ('SALES_EXECUTIVE', 'Sales Executive'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING_EXECUTIVE', 'Marketing Executive'), ('DIGITAL_MARKETING_SPECIALIST', 'Digital Marketing Specialist'), ('SEO_SPECIALIST', 'SEO Specialist'), ('ACCOUNTANT', 'Accountant'), ('FINANCE_MANAGER', 'Finance Manager'), ('AUDITOR', 'Auditor'), ('LEGAL_ADVISOR', 'Legal Advisor'), ('OPERATIONS_EXECUTIVE', 'Operations Executive'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('PROCUREMENT_EXECUTIVE', 'Procurement Executive'), ('TEAM_LEAD', 'Team Lead'), ('DELIVERY_MANAGER', 'Delivery Manager'), ('ENGINEERING_MANAGER', 'Engineering Manager'), ('DIRECTOR', 'Director'), ('VP_ENGINEERING', 'VP Engineering'), ('CTO', 'Chief Technology Officer'), ('CIO', 'Chief Information Officer'), ('COO', 'Chief Operating Officer'), ('CFO', 'Chief Financial Officer'), ('CEO', 'Chief Executive Officer'), ('CONSULTANT', 'Consultant'), ('FREELANCER', 'Freelancer'), ('CONTRACTOR', 'Contractor'), ('OTHERS', 'Others')], default='INTERN', max_length=50),
        ),
    ]
