# Generated by Django 5.1.5 on 2026-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HR_MANAGER', 'HR Manager'), ('ADMIN', 'Admin'), ('IT_SUPPORTER', 'IT Supporter'), ('MANAGER', 'Manager')], default='EMPLOYEE', max_length=50),
        ),
    ]
