# Generated by Django 5.1.5 on 2026-03-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_aadhaar_pan_gender_bloodgroup_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
