# Generated by Django 5.1.5 on 2026-02-17 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('DISPOSED', 'Disposed')], default='AVAILABLE', max_length=20)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('image_before', models.ImageField(blank=True, null=True, upload_to='assets/before/')),
                ('image_after', models.ImageField(blank=True, null=True, upload_to='assets/after/')),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('laptop_age', models.DurationField(blank=True, help_text='Duration the previous user used the asset', null=True)),
                ('is_under_repair', models.BooleanField(default=False, help_text='Is this asset currently under repair')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')])),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '4. Asset Assignment',
                'verbose_name_plural': '4. Asset Assignments',
            },
        ),
        migrations.CreateModel(
            name='AssetAssignmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assignments/')),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=10)),
                ('image', models.ImageField(upload_to='assets/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(help_text='Description of the issue/problem')),
                ('repair_notes', models.TextField(blank=True, help_text='Notes about the repair process')),
                ('repair_vendor', models.CharField(blank=True, help_text='Repair shop or vendor name', max_length=200)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of repair', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('AT_VENDOR', 'At Vendor'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When repair work started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When repair was finalized (Completed/Failed/Cancelled)', null=True)),
                ('estimated_completion', models.DateField(blank=True, help_text='Estimated completion date', null=True)),
            ],
            options={
                'verbose_name': '7. Asset Repair',
                'verbose_name_plural': '7. Asset Repairs',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='GOOD', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('return_image', models.ImageField(blank=True, null=True, upload_to='returns/')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_prefix', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('asset_team_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software')], default='HARDWARE', max_length=20)),
            ],
            options={
                'verbose_name': '1. Asset Type',
                'verbose_name_plural': '1. Asset Types',
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '8. Employee Status',
                'verbose_name_plural': '8. Employee Statuses',
            },
        ),
        migrations.CreateModel(
            name='OffboardingAssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='AVAILABLE', help_text='Condition of returned assets', max_length=20, verbose_name='Asset Return Status')),
                ('damaged_assets_file', models.FileField(blank=True, null=True, upload_to='offboarding/damaged_assets/', verbose_name='Damaged Assets File')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_offboarded', models.BooleanField(default=False, help_text='Mark this when offboarding process is completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '5. Offboarding Asset Return',
                'verbose_name_plural': '5. Offboarding Asset Returns',
                'ordering': ['-created_at'],
            },
        ),
    ]
