# Generated by Django 5.1.5 on 2025-10-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
            ],
            options={
                'verbose_name': '2. Hardware Asset',
                'verbose_name_plural': '2. Hardware Assets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
            ],
            options={
                'verbose_name': '3. Software Asset',
                'verbose_name_plural': '3. Software Assets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.AlterModelOptions(
            name='assetassignment',
            options={'verbose_name': '4. Asset Assignment', 'verbose_name_plural': '4. Asset Assignments'},
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'verbose_name': '1. Asset Type', 'verbose_name_plural': '1. Asset Types'},
        ),
        migrations.AlterModelOptions(
            name='employeestatus',
            options={'verbose_name': '6. Employee Status', 'verbose_name_plural': '6. Employee Statuses'},
        ),
        migrations.AddField(
            model_name='asset',
            name='laptop_age',
            field=models.DurationField(blank=True, help_text='Duration the previous user used the asset', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='previously_used_by',
            field=models.ForeignKey(blank=True, help_text='Previous user of the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchased_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettype',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software')], default='HARDWARE', max_length=20),
        ),
        migrations.CreateModel(
            name='OffboardingAssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='AVAILABLE', help_text='Condition of returned assets', max_length=20, verbose_name='Asset Return Status')),
                ('damaged_assets_file', models.FileField(blank=True, null=True, upload_to='offboarding/damaged_assets/', verbose_name='Damaged Assets File')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_offboarded', models.BooleanField(default=False, help_text='Mark this when offboarding process is completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returned_assets', models.ManyToManyField(blank=True, to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_offboarding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '5. Offboarding Asset Return',
                'verbose_name_plural': '5. Offboarding Asset Returns',
                'ordering': ['-created_at'],
            },
        ),
    ]
