# Generated by Django 5.2.1 on 2026-02-09 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='previously_used_by',
            field=models.ForeignKey(blank=True, help_text='Previous user of the asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
            ],
            options={
                'verbose_name': '2. Hardware Asset',
                'verbose_name_plural': '2. Hardware Assets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
            ],
            options={
                'verbose_name': '3. Software Asset',
                'verbose_name_plural': '3. Software Assets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('assets.asset',),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assets',
            field=models.ManyToManyField(related_name='assignments', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetassignmentimage',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetassignmentimage',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.assetassignment'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetimage',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetrepair',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetrepair',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_repairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_repair',
            field=models.ForeignKey(blank=True, help_text='Current active repair', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_asset', to='assets.assetrepair'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetreturn',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='assets.assetassignment'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='asset_types',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offboardingassetreturn',
            name='returned_assets',
            field=models.ManyToManyField(blank=True, to='assets.asset'),
        ),
        migrations.AddField(
            model_name='offboardingassetreturn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_offboarding_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assetrepair',
            index=models.Index(fields=['asset', 'status'], name='assets_asse_asset_i_715b55_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrepair',
            index=models.Index(fields=['status'], name='assets_asse_status_c96ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='assetrepair',
            index=models.Index(fields=['reported_at'], name='assets_asse_reporte_00ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['employee'], name='assets_asse_employe_db7bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['assigned_at'], name='assets_asse_assigne_a9d162_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_tag'], name='assets_asse_asset_t_42b762_idx'),
        ),
    ]
