# Generated by Django 5.1.5 on 2025-11-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_currently_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='currently_assigned_to',
        ),
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After')], max_length=10)),
                ('image', models.ImageField(upload_to='assets/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assets.asset')),
            ],
        ),
    ]
