# Generated by Django 5.1.5 on 2026-01-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_employeestatus_options_asset_is_under_repair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrepair',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When repair was finalized (Completed/Failed/Cancelled)', null=True),
        ),
        migrations.AlterField(
            model_name='assetrepair',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('AT_VENDOR', 'At Vendor'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
