# Generated by Django 5.1.5 on 2026-02-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelocationping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_location_pings', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancelocationping',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='biometricattendancelog',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='biometricattendancelog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='workfromhomerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wfh_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='workfromhomerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['biometric_user_id', 'date'], name='attendance__biometr_05e0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_337b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricattendancelog',
            index=models.Index(fields=['biometric_user_id', 'date'], name='attendance__biometr_fcf837_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricattendancelog',
            index=models.Index(fields=['date'], name='attendance__date_e356e3_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricattendancelog',
            index=models.Index(fields=['device_id', 'date'], name='attendance__device__d08b33_idx'),
        ),
    ]
