# Generated by Django 5.1.5 on 2026-02-09 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_check_in_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workfromhomerequest',
            old_name='request_date',
            new_name='end_date',
        ),
        migrations.AlterUniqueTogether(
            name='workfromhomerequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workfromhomerequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
