# Generated by Django 5.1.5 on 2026-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdevice',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='sync_interval_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
