# Generated by Django 5.2.1 on 2026-02-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_user_id', models.CharField(db_index=True, help_text='User ID from biometric device', max_length=100)),
                ('biometric_user_name', models.CharField(blank=True, help_text='User name from device if available', max_length=200)),
                ('device_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='biometric_user_id',
            field=models.CharField(blank=True, help_text='User ID from biometric device', max_length=100),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='biometric_user_name',
            field=models.CharField(blank=True, help_text='User name from biometric device', max_length=200),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_b6a945_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['biometric_user_id', 'date'], name='attendance__biometr_05e0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_337b1d_idx'),
        ),
        migrations.AddField(
            model_name='biometricattendancelog',
            name='attendance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='attendance.attendancerecord'),
        ),
        migrations.AddField(
            model_name='biometricattendancelog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='biometricattendancelog',
            index=models.Index(fields=['biometric_user_id', 'date'], name='attendance__biometr_fcf837_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricattendancelog',
            index=models.Index(fields=['date'], name='attendance__date_e356e3_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricattendancelog',
            index=models.Index(fields=['device_id', 'date'], name='attendance__device__d08b33_idx'),
        ),
    ]
