# Generated by Django 5.1.5 on 2026-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_biometricdevice_auto_sync_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevice',
            name='sync_interval_minutes',
            field=models.FloatField(default=15),
        ),
    ]
