# Generated by Django 5.1.5 on 2026-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_biometric_sync_interval_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='biometric_user_id',
            field=models.CharField(blank=True, help_text='User ID from biometric device', max_length=100, null=True),
        ),
    ]
