# Generated by Django 5.1.5 on 2026-02-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Access'), ('IT', 'IT Support'), ('ASSET_REPAIR', 'Asset Repair'), ('ACCESS', 'Access Request')], default='NEW', max_length=20, verbose_name='Request Type'),
        ),
    ]
