# Generated by Django 5.1.5 on 2026-01-30 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_assetrepair_completed_at_and_more'),
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='duration',
            field=models.IntegerField(blank=True, default=365, help_text='Access duration in days', null=True, verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Access'), ('IT', 'IT Support'), ('REPAIR', 'Asset Repair')], default='NEW', max_length=20, verbose_name='Request Type'),
        ),
    ]
