# Generated by Django 5.1.5 on 2026-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_accessrequest_asset_alter_accessrequest_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='asset',
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'New Access'), ('IT', 'IT Support')], default='NEW', max_length=20, verbose_name='Request Type'),
        ),
    ]
