# Generated by Django 5.1.5 on 2026-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0003_remove_accessrequest_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
