# Generated by Django 5.1.5 on 2025-06-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employee_type', models.CharField(choices=[('fresher', 'Fresher'), ('employee', 'Employee')], max_length=15)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_pan_collected', models.BooleanField(default=False, verbose_name='Aadhar and PAN Card')),
                ('aadhar_pan_file', models.FileField(blank=True, null=True, upload_to='documents/aadhar_pan/', verbose_name='Aadhar & PAN File')),
                ('payslips_collected', models.BooleanField(default=False, verbose_name="Last 6 months' payslips")),
                ('payslips_file', models.FileField(blank=True, null=True, upload_to='documents/payslips/', verbose_name='Payslips File')),
                ('educational_certificates_collected', models.BooleanField(default=False, verbose_name='Educational Certificates (Degree)')),
                ('educational_certificates_file', models.FileField(blank=True, null=True, upload_to='documents/educational_certificates/', verbose_name='Educational Certificates File')),
                ('previous_offer_letter_collected', models.BooleanField(default=False, verbose_name='Previous Offer Letter')),
                ('previous_offer_letter_file', models.FileField(blank=True, null=True, upload_to='documents/previous_offer_letter/', verbose_name='Previous Offer Letter File')),
                ('relieving_experience_letters_collected', models.BooleanField(default=False, verbose_name='Relieving & Experience Letters')),
                ('relieving_experience_letters_file', models.FileField(blank=True, null=True, upload_to='documents/relieving_experience/', verbose_name='Relieving & Experience Letters File')),
                ('appraisal_hike_letters_collected', models.BooleanField(default=False, verbose_name='Appraisal/Hike Letters ')),
                ('appraisal_hike_letters_file', models.FileField(blank=True, null=True, upload_to='documents/appraisal_hike/', verbose_name='Appraisal/Hike Letters File')),
            ],
            options={
                'verbose_name': 'Employee (Onboarding)',
                'verbose_name_plural': 'Employees (Onboarding)',
            },
        ),
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_date', models.DateField()),
                ('laptop_returned', models.BooleanField(default=False, verbose_name='Laptop')),
                ('charger_returned', models.BooleanField(default=False, verbose_name='Charger')),
                ('damaged_assets_file', models.FileField(blank=True, null=True, upload_to='offboarding/damaged_assets/', verbose_name='Damaged Assets File')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboardings', to='onboarding.employee')),
            ],
            options={
                'verbose_name': 'Employee Offboarding',
                'verbose_name_plural': 'Employee Offboarding',
            },
        ),
    ]
