# Generated by Django 5.1.5 on 2025-10-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_itsupporter_remove_employee_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Onboarding Link',
                'verbose_name_plural': '3. Onboarding Links',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee Onboarding', 'verbose_name_plural': '1. Employees Onboarding'},
        ),
        migrations.AlterModelOptions(
            name='offboarding',
            options={'verbose_name': 'Employee Offboarding', 'verbose_name_plural': '2. Employee Offboarding'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offboarding',
            name='charger_returned',
        ),
        migrations.RemoveField(
            model_name='offboarding',
            name='damaged_assets_file',
        ),
        migrations.RemoveField(
            model_name='offboarding',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='offboarding',
            name='laptop_returned',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_statements_collected',
            field=models.BooleanField(default=False, verbose_name='Last 6 months Bank Statements *'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_statements_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank_statements/', verbose_name='Bank Statements File *'),
        ),
        migrations.AddField(
            model_name='employee',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Company email address (will be used for system login)', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_address',
            field=models.TextField(blank=True, help_text='Current address including city, state, PIN code', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('development', 'Development'), ('design', 'Design'), ('qa', 'Quality Assurance'), ('support', 'Customer Support')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique employee username/ID for login', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Soft Deleted'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_self_submitted',
            field=models.BooleanField(default=False, verbose_name='Self Submitted by Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent address including city, state, PIN code', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', help_text='Include country code (e.g., +91 9876543210)', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submission Date'),
        ),
        migrations.AddField(
            model_name='offboarding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offboarding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offboarding',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar_pan_collected',
            field=models.BooleanField(default=False, verbose_name='Aadhar and PAN Card *'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='aadhar_pan_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar_pan/', verbose_name='Aadhar & PAN File *'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='appraisal_hike_letters_collected',
            field=models.BooleanField(default=False, verbose_name='Appraisal/Hike Letters (Optional)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='appraisal_hike_letters_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/appraisal_hike/', verbose_name='Appraisal/Hike Letters File (Optional)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='educational_certificates_collected',
            field=models.BooleanField(default=False, verbose_name='Educational Certificates (Degree) *'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='educational_certificates_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/educational_certificates/', verbose_name='Educational Certificates File *'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Personal email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('fresher', 'Fresher'), ('employee', 'Employee')], help_text='Will be set by HR during review', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payslips_collected',
            field=models.BooleanField(default=False, verbose_name="Last 6 months' payslips (Optional)"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payslips_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/payslips/', verbose_name='Payslips File (Optional)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('hr_manager', 'HR Manager'), ('hr_executive', 'HR Executive'), ('hr_intern', 'HR Intern'), ('it_manager', 'IT Manager'), ('system_admin', 'System Administrator'), ('network_engineer', 'Network Engineer'), ('it_support', 'IT Support'), ('senior_developer', 'Senior Developer'), ('junior_developer', 'Junior Developer'), ('full_stack_developer', 'Full Stack Developer'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('devops_engineer', 'DevOps Engineer'), ('tech_lead', 'Tech Lead'), ('ui_designer', 'UI Designer'), ('ux_designer', 'UX Designer'), ('graphic_designer', 'Graphic Designer'), ('qa_engineer', 'QA Engineer'), ('test_lead', 'Test Lead'), ('finance_manager', 'Finance Manager'), ('accountant', 'Accountant'), ('finance_executive', 'Finance Executive'), ('marketing_manager', 'Marketing Manager'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales Executive'), ('digital_marketer', 'Digital Marketer'), ('customer_support', 'Customer Support'), ('team_lead', 'Team Lead'), ('project_manager', 'Project Manager'), ('operations_manager', 'Operations Manager'), ('intern', 'Intern'), ('trainee', 'Trainee')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='previous_offer_letter_collected',
            field=models.BooleanField(default=False, verbose_name='Previous Offer Letter *'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='previous_offer_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/previous_offer_letter/', verbose_name='Previous Offer Letter File *'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='relieving_experience_letters_collected',
            field=models.BooleanField(default=False, verbose_name='Relieving & Experience Letters (Optional)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='relieving_experience_letters_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/relieving_experience/', verbose_name='Relieving & Experience Letters File (Optional)'),
        ),
    ]
