# Generated by Django 5.1.5 on 2026-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboardinglink_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Full Name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobile')),
                ('exp_years', models.PositiveIntegerField(default=0, verbose_name='Experience (Years)')),
                ('tech_stack', models.TextField(blank=True, help_text='Comma-separated list of technical skills', verbose_name='Tech Stack')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Current Location')),
                ('preferred_location', models.CharField(blank=True, max_length=200, verbose_name='Preferred Location')),
                ('experience', models.TextField(blank=True, verbose_name='Professional Summary')),
                ('cv_file', models.FileField(blank=True, help_text='PDF file stored locally; only the file path is saved in the database.', null=True, upload_to='cvs/', verbose_name='Resume (CV)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Candidate Resume',
                'verbose_name_plural': '4. Resume Management',
                'ordering': ['-created_at'],
            },
        ),
    ]
