# Generated by Django 5.1.5 on 2026-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_candidate_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tech Stack Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tech Stack',
                'verbose_name_plural': 'Tech Stacks',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='exp_years',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Experience (Years)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tech_stack',
            field=models.TextField(blank=True, help_text='Comma-separated list of technical skills extracted from PDF', verbose_name='Tech Stack (Raw)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tech_stacks',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='onboarding.techstack', verbose_name='Predefined Tech Stacks'),
        ),
    ]
