# Generated by Django 5.1.5 on 2026-02-17 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Deleted Employee',
                'verbose_name_plural': 'Deleted Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Onboarding Link',
                'verbose_name_plural': 'Onboarding Links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Include country code (e.g., +91 9876543210)', max_length=15)),
                ('employee_type', models.CharField(choices=[('fresher', 'Fresher'), ('employee', 'Employee')], max_length=15)),
                ('department', models.CharField(blank=True, choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('development', 'Development'), ('design', 'Design'), ('qa', 'Quality Assurance'), ('support', 'Customer Support')], max_length=20, null=True)),
                ('position', models.CharField(blank=True, choices=[('hr_manager', 'HR Manager'), ('hr_executive', 'HR Executive'), ('hr_intern', 'HR Intern'), ('it_manager', 'IT Manager'), ('system_admin', 'System Administrator'), ('network_engineer', 'Network Engineer'), ('it_support', 'IT Support'), ('senior_developer', 'Senior Developer'), ('junior_developer', 'Junior Developer'), ('full_stack_developer', 'Full Stack Developer'), ('frontend_developer', 'Frontend Developer'), ('backend_developer', 'Backend Developer'), ('devops_engineer', 'DevOps Engineer'), ('tech_lead', 'Tech Lead'), ('ui_designer', 'UI Designer'), ('ux_designer', 'UX Designer'), ('graphic_designer', 'Graphic Designer'), ('qa_engineer', 'QA Engineer'), ('test_lead', 'Test Lead'), ('finance_manager', 'Finance Manager'), ('accountant', 'Accountant'), ('finance_executive', 'Finance Executive'), ('marketing_manager', 'Marketing Manager'), ('sales_manager', 'Sales Manager'), ('sales_executive', 'Sales Executive'), ('digital_marketer', 'Digital Marketer'), ('customer_support', 'Customer Support'), ('team_lead', 'Team Lead'), ('project_manager', 'Project Manager'), ('operations_manager', 'Operations Manager'), ('intern', 'Intern'), ('trainee', 'Trainee')], max_length=30, null=True)),
                ('current_address', models.TextField(blank=True, help_text='Current address including city, state, PIN code', null=True)),
                ('permanent_address', models.TextField(blank=True, help_text='Permanent address including city, state, PIN code', null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Onboarding approval status', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Soft Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted Date')),
                ('is_self_submitted', models.BooleanField(default=False, verbose_name='Self Submitted by Employee')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submission Date')),
                ('it_notification_sent', models.BooleanField(default=False, verbose_name='IT Notification Sent')),
                ('aadhar_pan_collected', models.BooleanField(default=False, verbose_name='Aadhar and PAN Card')),
                ('aadhar_pan_file', models.FileField(blank=True, null=True, upload_to='documents/aadhar_pan/', verbose_name='Aadhar & PAN File')),
                ('payslips_collected', models.BooleanField(default=False, verbose_name="Last 6 months' payslips")),
                ('payslips_file', models.FileField(blank=True, null=True, upload_to='documents/payslips/', verbose_name='Payslips File')),
                ('educational_certificates_collected', models.BooleanField(default=False, verbose_name='Educational Certificates (Degree)')),
                ('educational_certificates_file', models.FileField(blank=True, null=True, upload_to='documents/educational_certificates/', verbose_name='Educational Certificates File')),
                ('previous_offer_letter_collected', models.BooleanField(default=False, verbose_name='Previous Offer Letter')),
                ('previous_offer_letter_file', models.FileField(blank=True, null=True, upload_to='documents/previous_offer_letter/', verbose_name='Previous Offer Letter File')),
                ('relieving_experience_letters_collected', models.BooleanField(default=False, verbose_name='Relieving & Experience Letters')),
                ('relieving_experience_letters_file', models.FileField(blank=True, null=True, upload_to='documents/relieving_experience/', verbose_name='Relieving & Experience Letters File')),
                ('appraisal_hike_letters_collected', models.BooleanField(default=False, verbose_name='Appraisal/Hike Letters ')),
                ('appraisal_hike_letters_file', models.FileField(blank=True, null=True, upload_to='documents/appraisal_hike/', verbose_name='Appraisal/Hike Letters File')),
            ],
            options={
                'verbose_name': 'Employee (Onboarding)',
                'verbose_name_plural': 'Employees (Onboarding)',
            },
        ),
        migrations.CreateModel(
            name='ITSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IT Supporter',
                'verbose_name_plural': 'IT Supporters',
            },
        ),
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_working_date', models.DateField()),
                ('laptop_returned', models.BooleanField(default=False, verbose_name='Laptop')),
                ('charger_returned', models.BooleanField(default=False, verbose_name='Charger')),
                ('damaged_assets_file', models.FileField(blank=True, null=True, upload_to='offboarding/damaged_assets/', verbose_name='Damaged Assets File')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboardings', to='onboarding.employee')),
            ],
            options={
                'verbose_name': 'Employee Offboarding',
                'verbose_name_plural': 'Employee Offboarding',
            },
        ),
    ]
